tiles/src/main/java/com/protomaps/basemap/layers/Places.java

sf.getString(“population”) may be null. Must check first if present before attempting to parse.

fix: Places.java parseIntOrNull

---

.github/workflows/maven.yml
.github/workflows/sonar.yml
tiles/pom.xml
tiles/sonar-project.properties

we want to match the same coverage/linting rules to ease upstreaming of code

add sonar config and GH actions to match planetiler

---

tiles/src/main/java/com/protomaps/basemap/layers/Roads.java
tiles/src/main/java/com/protomaps/basemap/layers/Transit.java

according to: https://wiki.openstreetmap.org/wiki/Lifecycle_prefix
This should remove some old, unused and removed railways/highways.
https://taginfo.openstreetmap.org/tags/razed%3Arailway
especially railways looked weird in my area without this filter
Todo: update docs (I didn't find them in this repo)

Filter old tracks

---

README.md
base/src/base_layers.ts
tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/main/java/com/protomaps/basemap/layers/Boundaries.java
tiles/src/main/java/com/protomaps/basemap/layers/Landuse.java
tiles/src/main/java/com/protomaps/basemap/layers/Natural.java
tiles/src/main/java/com/protomaps/basemap/layers/PhysicalLine.java
tiles/src/main/java/com/protomaps/basemap/layers/Places.java
tiles/src/main/java/com/protomaps/basemap/layers/Pois.java
tiles/src/main/java/com/protomaps/basemap/layers/Roads.java
tiles/src/main/java/com/protomaps/basemap/layers/Transit.java
tiles/src/main/java/com/protomaps/basemap/layers/Water.java
tiles/src/main/java/com/protomaps/basemap/names/NeNames.java

@bdon this captures most of what we talked about Monday.
TODO:
- **Places layer:** `population_rank` isn't working as expected
- **Places layer:** we need a better value to use for client side sorting. Normally this would be the Natural Earth min_zoom (which solves problems like San Francisco having a smaller population than Oakland)
- Fussy linting nits

[WIP] Basic schema enhancements for Felt basemap

---

tiles/src/main/java/com/protomaps/basemap/layers/Places.java

@nvkelso this ignores OSM population tag values that have commas in them (though we should either fix them upstream or handle those correctly)

tileset: fix population parsing of commas.

---

tiles/src/main/java/com/protomaps/basemap/layers/Roads.java

@nvkelso I think this is a bug; behavior as-is makes link features vanish z<12, which isn't what we want. Changes the behavior to only add the`pmap:link` tag at 12+.

stop road links from disappearing z < 12 [#53]

---

base/src/base_layers.ts

adds a `boundaries_country` layer for styling country boundaries with a solid line, as opposed to the dashed line that was used for all country/state/province boundaries

Add layer for country boundaries solid lines

---

tiles/src/main/java/com/protomaps/basemap/layers/Roads.java

Basic Java string manipulation change.
Fixes #86

hawaii state routes should not be US interstates

---

tiles/src/main/java/com/protomaps/basemap/layers/Pois.java

While the earlier logic did promote labels for international airports to earlier zooms, overall all airport labels were showing up too early. This change caps them to zoom 10 for international airports and zoom 12 for regional airports.

throttle back early airports

---

tiles/Makefile

The upside is better qualified data, the downside is significantly more prep time (hours or even a day).

Add Makefile targets for basic daylight and MSFT building sidecar

---

tiles/src/main/java/com/protomaps/basemap/layers/PhysicalLine.java
tiles/src/main/java/com/protomaps/basemap/layers/PhysicalPoint.java

Strait features were eligible for both physical_point and physical_line layers, producing duplicate horizontal point labels and oriented line labels in the same tile.
There should only ever be a single representation, and we should prefer the point label at this time. 
(In future we may want to generate curved lines suitable for labeling from the area, but right now we derive a label point instead.)
The result of this change keeps the blue circled node, but drops the red line.

Ensure strait labels are limited to single layer (and not any water polygon exterior rings)

---

tiles/src/main/java/com/protomaps/basemap/layers/Buildings.java
tiles/src/main/java/com/protomaps/basemap/layers/PhysicalLine.java
tiles/src/main/java/com/protomaps/basemap/layers/PhysicalPoint.java
tiles/src/main/java/com/protomaps/basemap/layers/Transit.java
tiles/src/main/java/com/protomaps/basemap/layers/Water.java

These should always be integers in tiles.

layer tags are all integers [#72]

---

tiles/pom.xml
tiles/src/main/java/com/protomaps/basemap/layers/Roads.java
tiles/src/main/java/com/protomaps/basemap/locales/CartographicLocale.java
tiles/src/main/java/com/protomaps/basemap/locales/US.java
tiles/src/test/java/com/protomaps/basemap/layers/RoadsTest.java
tiles/src/test/java/com/protomaps/basemap/locales/CartographicLocaleTest.java
tiles/src/test/java/com/protomaps/basemap/locales/USTest.java

@nvkelso this introduces the `CartographicLocale` class, that isn't dynamic yet (hardcoded to `US`) and adds tests around highway shield and network logic.

introduce Locales; always use US one for highway shields [#86, #92]

---

styles/src/base_layers.ts

@nvkelso it turns out having the wrong key `min_zoom` instead of `minzoom` is not only ineffective, it also silently breaks smooth style diffing! Weird. (TODO: figure out a better way to catch this with TypeScript)

Fix minzoom keys in base_layers

---

.github/workflows/maven.yml
.github/workflows/sonar.yml
README.md
tiles/pom.xml

I'm upgrading planetiler soon to require java 21 so am updating a few projects that use planetiler ahead of that.  This also unlocks using some [new features](https://advancedweb.hu/a-categorized-list-of-all-java-and-jvm-features-since-jdk-8-to-21/) that should make java little more ergonomic.

Use java 21

---

tiles/src/main/java/com/protomaps/basemap/layers/Pois.java

This PR fixes #163 by adding `highway=bus_stop` to the POIs
See https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbus_stop

Adds bus stops to POIs

---

app/src/MapViewComponent.tsx
app/src/VisualTestsComponent.tsx
styles/src/base_layers.ts

* refer to a font by a thematic name like Sans instead of the font name
* the specific font used is an implementation detail
* fonts are not versioned
* replaces Roboto latin with Noto for now, as we transition to final design choices

Replace cdn.protomaps.com fonts with github pages [#41]

---

tiles/src/main/java/com/protomaps/basemap/layers/Pois.java

@nvkelso @eikes 
We should document how this works at https://docs.protomaps.com/basemaps/layers 
notably, we need to be consistent about the mismatch between 256px NE/Leaflet zooms and MapLibre zooms. when we want bus stops to display at Z18 (MapLibre) we encode min_zoom = 17 in the tiles?

bus_stop zoom off by 1 [#163]

---

tiles/src/main/java/com/protomaps/basemap/layers/Boundaries.java

* We do our own generalization in code, so we don't need the generalized tables.
Fixes duplicate boundaries where multiple ne versions don't match up @nvkelso 
Before: (exaggerated overzoom)
After:

Only use ne_10m scale for boundaries [#119]

---

tiles/src/main/java/com/protomaps/basemap/layers/Boundaries.java
tiles/src/test/java/com/protomaps/basemap/layers/BoundariesTest.java

@nvkelso https://tilezen.readthedocs.io/en/latest/layers/#boundaries doesn't specify the type of `disputed`, I'm making it always boolean instead of integer since I don't see a point in values beyond true/false

Boundaries: make disputed boolean consistent [#190]

---

app/src/BuildsComponent.tsx

This adds more detail to the `/builds` page at maps.protomaps.com/builds

change color of monday build links; add planetiler layerstats links.

---

CHANGELOG.md
app/src/examples.json
tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/main/java/com/protomaps/basemap/layers/Landuse.java

See #180 
Refer to https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dbridge : 
> The tag [man_made](https://wiki.openstreetmap.org/wiki/Key:man_made)=bridge is used to tag a bridge defined by the outline of the bridge.
@wipfli @nvkelso

don't require man_made=bridge outlines have area=yes [#180]

---

app/src/examples.json
app/vite.config.ts
tiles/src/main/java/com/protomaps/basemap/layers/Boundaries.java

Boundaries admin level 3 5

---

tiles/src/main/java/com/protomaps/basemap/layers/Pois.java

* remove auto-incrementing integer as part of sort key
@nvkelso we need this to make the build byte-to-byte identical on the same inputs. The consistent sorting of ties should be handled internally.

POI layers in tiles is deterministic

---

CHANGELOG.md
tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/main/java/com/protomaps/basemap/layers/Buildings.java
tiles/src/test/java/com/protomaps/basemap/layers/BuildingsTest.java

Prerequisites for adding more tests around invalid heights like in #205

Test coverage for building heights [#205]

---

CHANGELOG.md
app/src/examples.json
tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/main/java/com/protomaps/basemap/layers/Water.java

We can't do any pre-filtering of water areas, because sometimes they are parts of linear features. Let the polygon merge routine do its work, and change the threshold to 1.0 pixels.

Simplify code and remove area filter for water features [#198]

---

app/package-lock.json
app/package.json
app/src/MapViewComponent.tsx

bump pmtiles to v3.x

---

tiles/src/main/java/com/protomaps/basemap/layers/Boundaries.java

Fixes #200.
OSM boundaries were quite detailed at mid- and high-zooms, and NE boundaries were a bit too detailed at low zooms.
Solution is to variably adjust the pixel tolerance from 0.1 to 0.4 to reduce file size and visual complexity, while preserving some details on fractional zoom in.
After:
Before:

fix #200 generalize boundaries line features

---

CHANGELOG.md
tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/main/java/com/protomaps/basemap/layers/Landcover.java
tiles/src/test/java/com/protomaps/basemap/layers/LandcoverTest.java

Connects with https://github.com/protomaps/basemaps/issues/154.
* Use geopackage mirror of daylight dataset from https://daylightmap.org/2023/10/11/landcover.html
* remap daylight classes to tilezen-like kinds

add daylight landcover to tileset [#154]

---

styles/package.json

* deprecate CommonJS build output
* rename IIFE to protomaps-themes-base.js
* rename ES6 module to index.js (exports value in package.json)

styles 2.0.0 [#231, #236]

---

styles/.gitignore
styles/src/index.ts
styles/test/custom_themes.test.ts
styles/test/index.test.ts

So far it was only possible to generate styles based on a set of fixed themes maintained by the protomaps project.
With this change, it is possible to pass a custom colour theme to create layers, without interfering with the final style. Also passing partial themes is possible to override only a small set of properties.
Example:
```ts
const myCustomTheme: Theme = {...}
const style = layersWithCustomTheme("protomaps", myCustomTheme)
```
or
```ts
const partialTheme: Partial<Theme> = { background: "#fff" };
const style = layersWithPartialCustomTheme(
"protomaps",
"dark", // use dark theme as base
partialTheme
);
```
Related issue: https://github.com/protomaps/basemaps/issues/224
This is just my take on addressing this problem. Please let me know if you have any suggestions or if you think …

Allow passing custom themes to create layers

---

tiles/src/main/java/com/protomaps/basemap/layers/Places.java
tiles/src/test/java/com/protomaps/basemap/layers/PlacesTest.java

Fixes #258.
Adds additional `locality` kind features to the **places** layer, namely with `pmap:kind_detail` in `locality`, `hamlet`, `isolated_dwelling`, `farm`, and `allotments`.
All of those except allotment were present in Tilezen but not yet included in Protomaps.

add missing "locality" places

---

tiles/Dockerfile
tiles/README.md

This sends the minimal build context to the container
add readme for mounting local volume to reuse downloads as well as write tiles to host.

add Dockerfile for building tiles [#184]

---

tiles/src/main/java/com/protomaps/basemap/layers/Roads.java

Due to https://github.com/protomaps/basemaps/pull/285 we currently do not have highways in the tiles below z12.
This pull requests fixes that, but we might want to add some sort of test to avoid this in the future.

Fix highways

---

CHANGELOG.md
tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/main/java/com/protomaps/basemap/layers/Places.java

This makes the `places` data rely purely on OSM for geometries, removing the buggy duplication of places and making name labels consistent at all zoom levels. @wipfli @nvkelso 
Since we allowlist the OSM name tags this keeps the tile size reasonable at low zooms 0-7.

Places: don't use Natural Earth at low zooms [#256, #282]

---

CHANGELOG.md
app/package-lock.json
app/package.json
app/src/MapViewComponent.tsx
styles/src/base_layers.ts
styles/src/language.ts

Breaking changes that remove the `pmap:` prefix and also remove the `physical_point`, `physical_line` and `natural` layers.

Styles 4.0.0

---

app/src/MapViewComponent.tsx
app/src/VisualTestsComponent.tsx
app/src/utils.ts
styles/src/base_layers.ts

set text-justify: auto on localities that might use a townspot symbol.

---

CHANGELOG.md
tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/main/java/com/protomaps/basemap/layers/Roads.java

@nvkelso this is to match https://tilezen.readthedocs.io/en/latest/layers/#road-transportation-kind_detail-values-and-zoom-ranges
> Ferries from both Natural Earth and OpenStreetMap are shown starting at zoom 5 with kind values of ferry.
as well as what's in http://tangrams.github.io/bubble-wrap/#15.595833333333331/37.7923/-122.3811

roads kind=ferry: filter by route=ferry instead of ferry=*. fixes [#312]

---

tiles/src/main/java/com/protomaps/basemap/layers/Buildings.java

fix typo `min_height` attributes in buildings layer

---

tiles/src/main/java/com/protomaps/basemap/layers/Water.java

Closes #329 
Let me preface by saying I don't know Java and I'm not very familiar with this codebase, so please excuse any amateur mistakes or oversights. I've marked this PR as a draft to ensure nobody mistakes me for someone who knows what they're doing.
As described in #329, the value of `kind` for oceanic features switches from `ocean` in z5 to `water` in z6. I think this inconsistency at different zoom levels is undesirable, and it precludes data users from being able to treat oceans differently from inland water. For example, in my own case, I'm wanting to use inland water data from the USGS rather than OSM for a US-focused map, while still using Natural Earth/OSMData for the oceans, but need a way to differentiate the two by attribute.
Since the water from the OSMData source only …

Change `kind` attribute of OSMData sourced-water to `ocean`

---

CHANGELOG.md
styles/package-lock.json
styles/package.json
styles/src/base_layers.ts

* Replace [geometry-type] with  to filter geometries correctly.

Fix geometry-type filter on water to be MapLibre v5 compatible.

---

tiles/src/main/java/com/protomaps/basemap/layers/Earth.java

Fixes https://github.com/protomaps/basemaps/issues/337
https://maps.protomaps.com/#map=0.97/-10.8/-17.6&theme=light&lang=en&tiles=https://protomaps.dev/~wipfli/antarctica.pmtiles

Fix Antarctica landcover

---

app/index.html
app/package-lock.json
app/package.json
app/src/Builds.tsx
app/src/MapView.tsx
app/src/VisualTests.tsx
app/tailwind.config.ts

> 1. The ‘Inspect button’ on the map, which serves as a toggle, doesn’t contain a clear value or indicator whether it is activated or not. This is needed for screen reader users to identify the current state of the toggle. This same issue occurs when opening or closing the ‘get style JSON’ button in the top navigation.
Added a label to maplibre-gl-inspect.
> 2. The two combo boxes above the map don’t have an accessible name, which means screen reader users will only hear ‘combo box German’ but can’t perceive the meaning of the combo box.
Added `label for=` HTML elements.
> 3. The radio buttons in the protomap builds page don’t have an accessible name. The screen reader will read ‘radio button checked 1 of 1’ but doesn’t say what this button is for.
Added `aria-label` indicating selected …

Fixes from accessibility audit.

---

app/src/MapView.tsx
app/src/index.css

* Display OSM IDs on right click/long press.
* Make the zooming to tile extents explicit.
* Fix changing of theme/lang when drag-and-drop files are loaded.

App improvements

---

app/src/MapView.tsx

Support TileJSON URLs in the app in addition to PMTiles URLs.

Support tilejson

---

CHANGELOG.md
tiles/pom.xml
tiles/src/main/java/com/protomaps/basemap/Basemap.java

By bumping Planetiler to v0.8.4, we can make use of the new Loop Line Merger in the FeatureMerge.mergeLineStrings function. It breaks small loops which reduces the chances of getting 3+ way junctions are intersections and roundabouts. Previously, the JTS line merging would not be able to merge at such 3+ way junctions and because of that, lines would not get merged at roundabouts and then they would be short and fall out of the tiles in the min length pruning. This led so far to a lot of gaps on `highway=primary` roads in particular.
Here are some screenshots:
https://pmtiles.io/?url=https%3A%2F%2Fprotomaps.dev%2F%7Ewipfli%2F365%2Fv4-0.8-SNAPSHOT.pmtiles#map=7.06/46.901/8.791
https://pmtiles.io/?url=https%3A%2F%2Fprotomaps.dev%2F%7Ewipfli%2F365%2Fv4-0.8.4-SNAPSHOT.pmtiles#map=7.06/46.901/8 …

Bump planetiler to v0.8.4

---

styles/src/index.ts

* this replaces all the previous methods with a single unified  function.
* this also enables tree-shaking theme objects for a smaller build.
Examples:
```js
// before
default("example","light","en")
// after
layers("example",namedTheme("light"),{lang:"en"})
```
```js
labels("example","light","en")
// after
layers("example",namedTheme("light"),{lang:"en",labelsOnly:true})
```
```js
layersWithCustomTheme("example",theme,"en")
// after
layers("example",theme,{lang:"en"})
```
```js
layersWithPartialCustomTheme("example",theme,"en")
// after
layers("example",{...theme,buildings:"red"},{lang:"en"})
```
```js
noLabelsWithCustomTheme("example",theme)
// after
layers("example",theme)
```
```js
labelsWithPartialCustomTheme("example",theme,"en")
// after …
```

new layers api for basemaps JS package.

---

app/src/Builds.tsx
app/src/MapView.tsx
app/src/utils.ts

Since we now have a different major version between the NPM package and the tileset.

Add callouts on compatible NPM versions on builds page.

---

tiles/src/main/java/com/protomaps/basemap/layers/Buildings.java

The current implementation is:
```
if( (sf.hasTag("building") && sf.canBePolygon()) || ... ){
... stuff ...
} else if (sf.hasTag("addr:housenumber")){
... actually add the housenumber ...
}
```
This means that a building (as polygon) will _never_ reach the else block where the address information is added. This means that the majority of buildings in Belgium (and many other countries) won't get address data included.
My fix is simply to remove this else. Note: I didn't test anything.

Update Buildings.java: remove "else" so that polygon-buildings with an address get address data too

---

CHANGELOG.md
tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/main/java/com/protomaps/basemap/layers/Earth.java
tiles/src/main/java/com/protomaps/basemap/layers/Water.java
tiles/src/test/java/com/protomaps/basemap/layers/EarthTest.java
tiles/src/test/java/com/protomaps/basemap/layers/WaterTest.java

Unify preprocessed feature ids on 0 so they can be better de-duplicated.

Better feature ids

---

tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/main/java/com/protomaps/basemap/layers/Boundaries.java
tiles/src/main/java/com/protomaps/basemap/layers/Buildings.java
tiles/src/main/java/com/protomaps/basemap/layers/Earth.java
tiles/src/main/java/com/protomaps/basemap/layers/Landcover.java
tiles/src/main/java/com/protomaps/basemap/layers/Landuse.java
tiles/src/main/java/com/protomaps/basemap/layers/Places.java
tiles/src/main/java/com/protomaps/basemap/layers/Pois.java
tiles/src/main/java/com/protomaps/basemap/layers/Roads.java
tiles/src/main/java/com/protomaps/basemap/layers/Transit.java
tiles/src/main/java/com/protomaps/basemap/layers/Water.java
tiles/src/test/java/com/protomaps/basemap/layers/LayerTest.java

Adds a `--layer` cli config option which allows you to process only a single layer. For example, to do only the roads you can use
```
--layer=roads
```

`--layer` cli config option

---

tiles/src/main/java/com/protomaps/basemap/layers/Roads.java

When writing the road relation pull request I forgot that trunk_link and trunk should have the same minzoom, similar to motorway and motorway_link...

Fix trunk link minzoom

---

tiles/src/main/java/com/protomaps/basemap/layers/Roads.java
tiles/src/test/java/com/protomaps/basemap/layers/RoadsTest.java

Adds some unit tests for the roads layer. Not covered is:
* minZoomNames
* minZoomShieldText
* links
* tunnels
With the current test infrastructure I don't know how to easily test attributes that have a min zoom like 
```
.setAttrWithMinzoom("shield_text_length", shieldTextLength, minZoomShieldText)
```
One can supply a zoom to `assertFeatures` but then to check if the min zoom is correct one sort of needs to check the presence at minZoom and the absence at minZoom-1, but I don't know how to test for the absence of an attribute...
Anyway, this increases coverage already quite a bit.

roads unittests

---

tiles/pom.xml

Makes us use planetiler releases from maven which are more stable than the snapshots from sonatype.

Use planetiler releases instead of snapshots

---

tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/main/java/com/protomaps/basemap/feature/Matcher.java
tiles/src/main/java/com/protomaps/basemap/layers/Earth.java
tiles/src/main/java/com/protomaps/basemap/layers/Landcover.java
tiles/src/main/java/com/protomaps/basemap/layers/Landuse.java
tiles/src/main/java/com/protomaps/basemap/layers/Water.java
tiles/src/test/java/com/protomaps/basemap/feature/MatcherTest.java
tiles/src/test/java/com/protomaps/basemap/layers/EarthTest.java
tiles/src/test/java/com/protomaps/basemap/layers/LandcoverTest.java
tiles/src/test/java/com/protomaps/basemap/layers/WaterTest.java

Copied filter rules from tilezen's water.yaml file. Each copied filter rule was marked with "done". Each skipped item was marked with "skip" in https://github.com/wipfli/vector-datasource/pull/1
Skipped are the following
- NE coast lines
- intermittent
- boat
- reservoir
- alkaline
Rules in tilezen were evaluated top to bottom, we do pick the last. So I reversed the order of the filter rules, e.g., covered=yes appears last here, in tilezen it was first...

water matcher

---

CHANGELOG.md
tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/main/java/com/protomaps/basemap/layers/Earth.java
tiles/src/main/java/com/protomaps/basemap/layers/Landcover.java
tiles/src/main/java/com/protomaps/basemap/layers/Water.java
tiles/src/test/java/com/protomaps/basemap/layers/EarthTest.java
tiles/src/test/java/com/protomaps/basemap/layers/LandcoverTest.java
tiles/src/test/java/com/protomaps/basemap/layers/WaterTest.java

* assign IDs based on landcover class
https://github.com/onthegomap/planetiler/blob/main/planetiler-core/src/main/java/com/onthegomap/planetiler/VectorTile.java#L88 is where 0 never makes it into the vector tiles, which also screws up IDs after post process-merging.

use vector tile id=1 since 0 is special cased.

---

tiles/src/main/java/com/protomaps/basemap/layers/Earth.java

make sure taiwan and most of the philippine archipelago shows up at zoom=0 instead of disappearing. 
The planet build size is 120.3 GB

set min earth size back to 1px

---

styles/src/index.ts

I've had to fork the style to customise it, but it would be nicer to import these functions rather than copy them.

Export get_multiline_name and get_country_name

---

CHANGELOG.md
examples/basic.html
examples/data_sandwich.html
examples/theme_language.html
styles/package-lock.json
styles/package.json
styles/src/base_layers.ts
tiles/src/main/java/com/protomaps/basemap/Basemap.java

@wipfli without this we get console warnings `Expected value to be of type number, but found null instead.` if the style depends on `sort_rank` but the tileset is a 4.x that doesn't contain it.
If we didn't want to do this then we would require a SemVer bump for this kind of change which seems painful.

Make the style work with older tile builds missing sort_rank [#436]

---

styles/src/base_layers.ts

MapLibre GL can place text labels such that the anchor, i.e., the icon/symbolizer location, is to the left, right, top, or bottom of the label. So far we are only using labels where the anchor is to the left.
This pull request proposes to have a variable anchor, with bottom taking precedence over left, and right. As a result, more labels can be shown which is convenient in dense areas.
Demo: https://wipfli.github.io/debug-assets/text-variable-anchor/index.html#map=1.99/0/0

Use text-variable-anchor

---

app/src/MapView.tsx

@wipfli this is to work around a Safari issue which I think is a race condition - the map initialization and size detection completes before the CSS stylesheet is loaded, meaning that the map is initialized to the wrong size. I consistently see this in Vite-based MapLibre applications only on Safari/Mobile Safari, so this is a hack that calls resize once the map is loaded.

app: resize map on load to work around Safari CSS issues

---

tiles/src/main/java/com/protomaps/basemap/layers/Boundaries.java
tiles/src/main/java/com/protomaps/basemap/layers/Buildings.java
tiles/src/main/java/com/protomaps/basemap/layers/Earth.java
tiles/src/main/java/com/protomaps/basemap/layers/Landcover.java
tiles/src/main/java/com/protomaps/basemap/layers/Landuse.java
tiles/src/main/java/com/protomaps/basemap/layers/Places.java
tiles/src/main/java/com/protomaps/basemap/layers/Pois.java
tiles/src/main/java/com/protomaps/basemap/layers/Roads.java
tiles/src/main/java/com/protomaps/basemap/layers/Water.java

We have 83 open issues related to S1192 duplicated string literals: https://sonarcloud.io/project/issues?rules=java%3AS1192&issueStatuses=OPEN%2CCONFIRMED&id=protomaps_basemaps
Those should all be closed with this pull request, bringing the total sonar issue count down from 164 to 81.

Suppress duplicated string literals warning in layer classes

---

tiles/src/main/java/com/protomaps/basemap/Basemap.java

Though that method is deprecated:
```
Planetiler com.onthegomap.planetiler.Planetiler.addNaturalEarthSource(String name, Path defaultPath, String defaultUrl)
Deprecated. can be replaced by addGeoPackageSource(String, Path, String).
Adds a new Natural Earth sqlite file source that will be processed when run() is called.
If the file does not exist and download=true argument is set, then the file will first be downloaded from defaultUrl.
To override the location of the sqlite file, set name_path=newpath.zip in the arguments and to override the download URL set name_url=http://url/of/natural_earth.zip.
```
@msbarry the build crashed when replacing natural earth with geopackage source. Do you have an example of how this should be done?

Revert addGeopackage to addNaturalEarthSource

---

tiles/Dockerfile

It was kind of annoying to me, doing a complete refetch of the dependencies on each build within docker.

chore: improved Dockerfile to utilize cached layers

---

.github/workflows/maven.yml
CHANGELOG.md

Fixes CI on main which currently fails like this:

Do not run tile version bump check on main
