README.md

Just a minor typo I stumbled upon :)

Fix project path typo in README.md

---

tiles/src/main/java/com/protomaps/basemap/layers/Roads.java
tiles/src/test/java/com/protomaps/basemap/layers/RoadsTest.java

@nvkelso 
This also starts fleshing out unit tests on layers

layers attr on roads is integer [#72]

---

tiles/src/main/java/com/protomaps/basemap/layers/Roads.java

exclude elevator lines from roads layer

---

tiles/src/main/java/com/protomaps/basemap/layers/Places.java

Adjust places layer thinning

---

base/src/base_layers.ts

Update font names
Change fonts to point to cdn.protomaps.com with same output as https://github.com/maplibre/font-maker
Remove mask layer

Noto sans font names

---

tiles/src/main/java/com/protomaps/basemap/feature/QrankDb.java
tiles/src/test/java/com/protomaps/basemap/feature/QrankDbTest.java

handle multiple or misformatted wikidata id [#117]

---

README.md

@nvkelso take a look to see if LGTM

New licensing and attribution guidelines.

---

app/src/MapViewComponent.tsx
app/src/index.css

* make dropzone a lot smaller and its own element.

fix file dialog opening on panning in firefox/chromium

---

README.md

* Specify URL to load locally generated pmtiles
* Mention the usage of npm install

Update local dev docs

---

app/src/MapViewComponent.tsx
app/src/index.css
tiles/src/main/java/com/protomaps/basemap/Basemap.java

add a max height to basemap inspect popup

---

CHANGELOG.md
tiles/src/main/java/com/protomaps/basemap/Basemap.java

Tiles v3.1.0

---

tiles/src/main/java/com/protomaps/basemap/layers/Landuse.java
tiles/src/test/java/com/protomaps/basemap/layers/LanduseTest.java

Closes #204 
I'm not yet 100% sure about the playgrounds, they seem to be included, just not rendered on the map. Will check details tomorrow.
@nvkelso  Regarding POIs - I think adding the landuse to POIs does not make sense, right?

adds landuse=village_green and landuse=allotments

---

CHANGELOG.md
app/src/examples.json
styles/package-lock.json
styles/package.json
styles/src/base_layers.ts
tiles/src/main/java/com/protomaps/basemap/Basemap.java

* add landuse_urban_green layer to styles for village_green, allotments, playgrounds

Tiles 3.4.0; Styles 2.0.0-alpha.5

---

styles/package-lock.json
styles/package.json

* package.json improvements for es6 module default
* specify files in package.json
* remove esbuild-runner in favor of tsx

v2.0.0-alpha.6 - fix publint [#231]

---

CHANGELOG.md
app/package-lock.json
app/package.json
tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/main/java/com/protomaps/basemap/layers/Landcover.java
tiles/src/test/java/com/protomaps/basemap/layers/LandcoverTest.java

* Order landcover by kind consistently

Landcover 2

---

tiles/src/main/java/com/protomaps/basemap/Basemap.java

Reintroduce Natural Earth Downloader

---

app/package-lock.json
app/package.json
app/src/MapViewComponent.tsx
app/vite.config.ts

* remove OpenLayers from demo page.
* add local sprites checkbox.

Remove ol add local sprites checkbox

---

styles/package-lock.json
styles/package.json

* emit the CommonJS build as index.cjs.

Add CommonJS build target back. [#231]

---

tiles/src/main/java/com/protomaps/basemap/layers/Transit.java

Fix #249: ignore buildings in transit.java

---

CHANGELOG.md
tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/test/java/com/protomaps/basemap/layers/TransitTest.java

* add test for transit exclude buildings

Tiles 3.5.2

---

tiles/src/main/java/com/protomaps/basemap/layers/Places.java
tiles/src/main/java/com/protomaps/basemap/names/NeNames.java
tiles/src/main/java/com/protomaps/basemap/names/OsmNames.java
tiles/src/main/java/com/protomaps/basemap/names/Script.java
tiles/src/test/java/com/protomaps/basemap/names/ScriptTest.java

Add pmap:script

---

CHANGELOG.md
tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/main/java/com/protomaps/basemap/names/Script.java

Tiles 3.6.0

---

tiles/pom.xml

Should we also switch to java 22?

Bump planetiler

---

tiles/src/test/java/com/protomaps/basemap/names/ScriptTest.java

Taken from this Github comment https://github.com/protomaps/basemaps/pull/254#issuecomment-2144007634 (which was getting lost) and additional research

Add better inline docs for langauage scripts

---

.github/FUNDING.yml
.github/pull_request_template.md

Clean up .github dir

---

CHANGELOG.md
styles/package-lock.json
styles/package.json
styles/tsup.config.ts

switch to tsup for building style outputs [#231]

---

tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/main/java/com/protomaps/basemap/names/OsmNames.java
tiles/src/test/java/com/protomaps/basemap/names/OsmNamesTest.java

We want to limit the names to only those the style will support for localization.

Initial list of allowed name:* tags [#112,#270]

---

app/src/BuildsComponent.tsx
app/src/MapViewComponent.tsx

Add viewer checkbox to show/hide tile and label bboxes
Freeze tileset version at 9/17 to prepare for breaking change

Show boxes

---

app/src/BuildsComponent.tsx
app/src/MapViewComponent.tsx
tiles/Makefile

* add builds link
* builds page uses latest style for maperture
* remove daylight parts of makefile

viewer fixes

---

tiles/src/main/java/com/protomaps/basemap/layers/Boundaries.java
tiles/src/main/java/com/protomaps/basemap/layers/Buildings.java
tiles/src/main/java/com/protomaps/basemap/layers/Earth.java
tiles/src/main/java/com/protomaps/basemap/layers/Landcover.java
tiles/src/main/java/com/protomaps/basemap/layers/Places.java
tiles/src/main/java/com/protomaps/basemap/layers/Pois.java
tiles/src/main/java/com/protomaps/basemap/layers/Roads.java
tiles/src/main/java/com/protomaps/basemap/layers/Water.java
tiles/src/main/java/com/protomaps/basemap/postprocess/Area.java
tiles/src/main/java/com/protomaps/basemap/postprocess/LinkSimplify.java
tiles/src/test/java/com/protomaps/basemap/postprocess/LinkSimplifyTest.java

Just refactoring and correctness/tests.

Fix deprecations; fix NPE in linkSimplify

---

sprites/themes/dark.json
sprites/themes/light.json

Add initial set of green sprites.

Green sprites

---

CHANGELOG.md
app/src/MapViewComponent.tsx
app/src/VisualTestsComponent.tsx
app/src/examples.json
styles/package-lock.json
styles/package.json
styles/src/base_layers.ts
styles/src/generate_styles.ts
styles/src/themes.ts

Styles 4 1

---

app/src/MapViewComponent.tsx

app: fetch from Tigris bucket by default instead of slow R2 build archive

---

LICENSE.md
README.md

Add license details for sprites.

---

styles/src/base_layers.ts
styles/src/language.ts
styles/src/themes.ts

Make fonts a theme parameter, add landcover and more poi colors in theme object

---

CHANGELOG.md
styles/src/base_layers.ts
styles/src/themes.ts

* adjust light earth color
* adjust POI text scaling at z17+

styles 4.2; add initial set of lapis and slategray icons. [#238]

---

.github/workflows/app.yml
app/src/Builds.tsx
app/src/MapView.tsx

* fix height and always show attribution on mobile.
* add linting to CI

Show timeliness information on the bottom left of map view.

---

examples/basic.html
examples/data_sandwich.html
examples/theme_language.html
styles/package-lock.json
styles/package.json
styles/src/base_layers.ts
styles/src/themes.ts

* give all text halos
* fix smallest font size of lakes
* remove halo-blur
* clean up dashed appearance of boundaries at low zooms

Styles 4 4

---

CHANGELOG.md
tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/main/java/com/protomaps/basemap/layers/Buildings.java
tiles/src/test/java/com/protomaps/basemap/layers/BuildingsTest.java

Add unit test for #387 and bump tileset version to 4.3.1

Address centroid tests

---

tiles/src/main/java/com/protomaps/basemap/layers/Landuse.java
tiles/src/test/java/com/protomaps/basemap/layers/LanduseTest.java

Adds unit tests for the landuse `kind` selection logic.

landuse unittests

---

styles/package-lock.json
styles/package.json

Update package-lock.json in styles

---

CHANGELOG.md
styles/src/base_layers.ts
tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/main/java/com/protomaps/basemap/layers/Landuse.java
tiles/src/main/java/com/protomaps/basemap/layers/Water.java
tiles/src/test/java/com/protomaps/basemap/layers/LanduseTest.java
tiles/src/test/java/com/protomaps/basemap/layers/WaterTest.java

* fix natural=grassland in landuse [#405]

* Add kind=dam to landuse, remove from water [#404]

---

CHANGELOG.md
examples/basic.html
examples/data_sandwich.html
examples/theme_language.html
styles/package-lock.json
styles/package.json
styles/src/index.ts
tiles/src/main/java/com/protomaps/basemap/Basemap.java

tiles 4.8.1, styles 5.0.2

---

styles/src/base_layers.ts
tiles/src/main/java/com/protomaps/basemap/layers/Places.java

Fixes #286 #256 
Merge after #434

places sort key

---

CHANGELOG.md
styles/src/base_layers.ts
tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/main/java/com/protomaps/basemap/layers/Places.java

Copies the pre-collide changes from #300 over to latest main.

places grid

---

tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/main/java/com/protomaps/basemap/layers/Boundaries.java
tiles/src/main/java/com/protomaps/basemap/layers/Roads.java
tiles/src/main/java/com/protomaps/basemap/text/FontRegistry.java
tiles/src/main/java/com/protomaps/basemap/text/TextEngine.java

Fixes some sonar issues tagged "cert". Note that some of those overlap with the "unused" issues which are fixed in a different pull request.
https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&tags=cert&id=protomaps_basemaps

Fix sonar cert issues

---

tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/main/java/com/protomaps/basemap/layers/Boundaries.java
tiles/src/main/java/com/protomaps/basemap/layers/Buildings.java
tiles/src/main/java/com/protomaps/basemap/layers/Earth.java
tiles/src/main/java/com/protomaps/basemap/layers/Landuse.java
tiles/src/main/java/com/protomaps/basemap/layers/Places.java
tiles/src/main/java/com/protomaps/basemap/layers/Pois.java
tiles/src/main/java/com/protomaps/basemap/layers/Water.java

Fixes some sonar cloud issues tagged "unused". https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&issueStatuses=OPEN%2CCONFIRMED&tags=unused&id=protomaps_basemaps

Remove unused code

---

tiles/src/main/java/com/protomaps/basemap/text/FontRegistry.java
tiles/src/main/java/com/protomaps/basemap/text/TextEngine.java
tiles/src/test/java/com/protomaps/basemap/text/TextEngineTest.java

Fixes some bad practice tagged sonar issues, see https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&tags=bad-practice&id=protomaps_basemaps

Fix sonar bad practice issues

---

CHANGELOG.md
tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/main/java/com/protomaps/basemap/layers/Boundaries.java

Tiles 4.11.3

---

tiles/src/main/java/com/protomaps/basemap/layers/Boundaries.java
tiles/src/main/java/com/protomaps/basemap/layers/Roads.java
tiles/src/main/java/com/protomaps/basemap/locales/CartographicLocale.java
tiles/src/main/java/com/protomaps/basemap/locales/US.java
tiles/src/main/java/com/protomaps/basemap/names/Script.java
tiles/src/main/java/com/protomaps/basemap/names/ScriptSegmenter.java
tiles/src/main/java/com/protomaps/basemap/text/TextEngine.java
tiles/src/test/java/com/protomaps/basemap/names/ScriptSegmenterTest.java
tiles/src/test/java/com/protomaps/basemap/text/FontRegistryTest.java
tiles/src/test/java/com/protomaps/basemap/text/TextEngineTest.java

Before this pull request we are at 65 issues on the main branch, after we will probably be at around 40. I suggest we leave the issues that remain as is, so this would be the last pull request on sonar issue fixes.

Fix more sonar issues

---

CHANGELOG.md
tiles/pom.xml
tiles/src/main/java/com/protomaps/basemap/Basemap.java
tiles/src/main/java/com/protomaps/basemap/feature/QrankDb.java

Tiles 4.11.5; bump planetiler

---

examples/basic.html
examples/data_sandwich.html
examples/theme_language.html
styles/package-lock.json
styles/package.json
styles/src/base_layers.ts

* This caused boundaries to not appear on maplibre-native.

Ensure line-dasharray has at least two elements [#502]
